name: operator

permissions:
  - applications:get
  - applications:sync
  - applications:action
  - applications:delete
  - logs:get
  - repositories:get
  - repositories:create
  - repositories:update
  - repositories:delete