{{- if eq .Values.cluster "management" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
{{- range $groupFile, $_ := .Files.Glob "groups/*.yaml" }}
{{- $group := fromYaml ($.Files.Get $groupFile) }}
{{- range $perm := $group.globalPermissions }}
{{- $parts := splitList ":" $perm }}
    p, {{ $group.name }}, {{ index $parts 0 }}, {{ index $parts 1 }}, *, allow
{{- end }}
{{- end }}
{{- end }}